version: "3.8"

volumes:
  registry:
    external: true
    name: "rinnegan-registry-data"

networks:
  registry:
    external: true
    name: "rinnegan-registry"

services:
  registry:
    container_name: rinnegan-registry
    image: rinnegan-registry
    networks:
      - registry
    ports:
      - 5000:5000
    volumes:
      - registry:/data
    build:
      context: .
